language: csharp
mono: none
dist: trusty
dotnet: 1.1.5
install:
  - dotnet msbuild /t:Clean
  - dotnet msbuild /t:Restore
script:
  - dotnet msbuild /t:Build
  - dotnet test QueryBuilder.Tests/QueryBuilder.Tests.csproj --no-build
